### ISSUE TITLE
Since 4.0.0 composer's files entries are lazy loaded

### ISSUE THREAD

**Issue by jails** [ezzatron/phony-kahlan#1]
Hello,
Since Kahlan 4.0.0 composer's files are now lazy loaded to be able to perform some JIT patching on them. So running `Eloquent\Phony\Kahlan\install()` right in `kahlan-config.php` won't work out of the box since files aren't loaded yet.

However you can wrap the call inside a filter so the phony installation will be lazily loaded just before specs are ran.

```php
<?php
use Kahlan\Filter\Filters;

Filters::apply($this, 'run', function($chain) {
    Eloquent\Phony\Kahlan\install();
    return $chain();
});
```

**Comment by ezzatron** [comment]
Ah, no worries. Thanks for letting me know!

**Comment by ezzatron** [comment]
@jails Would it also make sense to recommend that people use:

```php
$this->commandLine()->set('exclude', ['Eloquent\Phony']);
```

I can't imagine a use-case where someone would really want to use monkey patching on Phony's classes.
